import smtplib
import time
from email.message import EmailMessage
from dotenv import load_dotenv
import os

load_dotenv()

GMAIL_USER = os.getenv("GMAIL_USER") #SENDER's MAIL
APP_PASSWORD = os.getenv("APP_PASSWORD")
TO_EMAIL = os.getenv("TO_EMAILS").split(",") #RECIEVER's MAIL


def send_fraud_email(row):
    msg = EmailMessage()
    msg["Subject"] = f"🚨 Fraud Alert - Step {row['step']}"
    msg["From"] = GMAIL_USER
    msg["To"] = ", ".join(TO_EMAIL)

    # Plain text fallback
    msg.set_content(f"""
⚠️ A fraudulent transaction has been detected!

Transaction Summary:
---------------------
Type: {row['type']}
Amount: ₹{row['amount']}
Step: {row['step']}
Sender: {row['nameOrig']}
Old Balance (Sender): ₹{row['oldbalanceOrg']}
New Balance (Sender): ₹{row['newbalanceOrig']}
Receiver: {row['nameDest']}
Old Balance (Receiver): ₹{row['oldbalanceDest']}
New Balance (Receiver): ₹{row['newbalanceDest']}

Generated by the UPI Fraud Detection Model Created by Minit Chitroda.
""")

    # HTML content
    html = f"""
    <html>
      <body style="font-family: 'Segoe UI', sans-serif; background-color: #f4f6f8; padding: 20px;">
        <div style="max-width: 600px; margin: auto; background-color: #fff; border-radius: 8px; box-shadow: 0 2px 5px rgba(0,0,0,0.1); padding: 20px; border-left: 5px solid #c0392b;">
          <h2 style="color: #c0392b;">🚨 Fraudulent Transaction Detected</h2>
          <p style="font-size: 15px;">The following transaction was flagged as potentially fraudulent:</p>
          <table style="width: 100%; border-collapse: collapse; margin-top: 15px;">
            <tr><td style="padding: 8px;"><strong>Step</strong></td><td>{row['step']}</td></tr>
            <tr><td style="padding: 8px;"><strong>Type</strong></td><td>{row['type']}</td></tr>
            <tr><td style="padding: 8px;"><strong>Amount</strong></td><td>₹{row['amount']}</td></tr>
            <tr><td style="padding: 8px;"><strong>Sender</strong></td><td>{row['nameOrig']}</td></tr>
            <tr><td style="padding: 8px;"><strong>Old Balance (Sender)</strong></td><td>₹{row['oldbalanceOrg']}</td></tr>
            <tr><td style="padding: 8px;"><strong>New Balance (Sender)</strong></td><td>₹{row['newbalanceOrig']}</td></tr>
            <tr><td style="padding: 8px;"><strong>Receiver</strong></td><td>{row['nameDest']}</td></tr>
            <tr><td style="padding: 8px;"><strong>Old Balance (Receiver)</strong></td><td>₹{row['oldbalanceDest']}</td></tr>
            <tr><td style="padding: 8px;"><strong>New Balance (Receiver)</strong></td><td>₹{row['newbalanceDest']}</td></tr>
          </table>
          <p style="margin-top: 20px; font-size: 13px; color: #555;">
            <em>This alert was auto-generated by the UPI Fraud Detection Model developed by <strong>Minit Chitroda</strong>.</em>
          </p>
        </div>
        <p style="text-align: center; font-size: 11px; color: #999; margin-top: 30px;">
          © {time.strftime("%Y")} UPI Fraud Monitoring System | All rights reserved.
        </p>
      </body>
    </html>
    """
    msg.add_alternative(html, subtype='html')

    try:
        with smtplib.SMTP_SSL("smtp.gmail.com", 465) as smtp:
            smtp.login(GMAIL_USER, APP_PASSWORD)
            smtp.send_message(msg)
            print(f"📧 Email alert sent for step {row['step']}")
    except Exception as e:
        print(f"❌ Email send failed: {e}")
